### ISSUE TITLE
DFU example

### ISSUE THREAD

**Issue by jacobrosenthal** [ARMmbed/ble-examples#16]
I added dfu service to a heartrate example:
https://github.com/jacobrosenthal/ble-examples/tree/dfu-heartrate

and Im generating the .dat file with a script I mostly cribbed from a Nordic post
https://github.com/jacobrosenthal/redbearlab-nrf51822-gcc/blob/master/scripts/generate_dat.py

Im using the guide here to srec softdevice, application, and bootloader together (do we have a python alternative to srec?)
https://developer.mbed.org/forum/team-63-Bluetooth-Low-Energy-community/topic/5201/
Also, Im using the nrf51822/bootloader/s130_nrf51_1.0.0_bootloader.hex, is that correct?
```
srec_cat yotta_targets/nordic-nrf51822-16k-gcc/softdevice/s130_nrf51_1.0.0_softdevice.hex -intel build/redbearlab-nrf51822-gcc/source/ble-heartrate.hex -intel \
yotta_modules/ble-nrf51822/bootloader/s130_nrf51_1.0.0_bootloader.hex -intel -exclude 0x3FC00 \
0x3FC20 -generate 0x3FC00 0x3FC04 -l-e-constant 0x01 4 -generate \
0x3FC04 0x3FC08 -l-e-constant 0x00 4 -generate 0x3FC08 0x3FC0C \
-l-e-constant 0xFE 4 -generate 0x3FC0C 0x3FC20 -constant 0x00 -o \
combined.hex -intel
```
The application runs and I can see the DFU service, but writing to it doesn't ever bring the device back as DFUTarg.

However, if I dont add in the application hex, the bootloader DFUTarg does show up and Im able to write application hex to it, but of course, then the same thing occurs and Its DFU service doesnt allow DFU a second time.
```
srec_cat yotta_targets/nordic-nrf51822-16k-gcc/softdevice/s130_nrf51_1.0.0_softdevice.hex -intel yotta_modules/ble-nrf51822/bootloader/s130_nrf51_1.0.0_bootloader.hex -intel -exclude 0x3FC00 0x3FC20 -generate 0x3FC00 0x3FC04 -l-e-constant 0x01 4 -generate 0x3FC04 0x3FC08 -l-e-constant 0x00 4 -generate 0x3FC08 0x3FC0C -l-e-constant 0xFE 4 -generate 0x3FC0C 0x3FC20 -constant 0x00 -o combined.hex -intel
```

Id obviously love to push all this upstream when its working, into an example or a target, or wherever you think it belongs. I have another post here about target inheritance
http://forums.mbed.com/t/post-build-hooks-toolchain-cmake-and-inheriting-from-targets/694

**Comment by rgrover** [comment]
@jacobrosenthal thanks for test-driving DFU in conjunction with mbed OS.

I'll answer the easy ones first:
Python alternative to srec: https://github.com/ARMmbed/target-nrf51822/blob/master/nordic-nrf51822-32k-gcc/scripts/merge_hex.py

nrf51822/bootloader/s130_nrf51_1.0.0_bootloader.hex is the correct bootloader. At least we've verified this with mbed-classic.

Your command to generate the combined.hex looks correct.

Given that you are able to work the bootloader for DFU if you don't add the application, it means that the bootloader and softdevice combination are correct.  What happens if you DFU an mbed-classic application?

We haven't yet tested nordic-DFU in conjunction with mbed OS. We'll need a few days to get back to you on this. In the mean time, can you experiment with DFU'ing in an mbed-classic app?

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSFW-1198

**Comment by jacobrosenthal** [comment]
It doesnt look like hexmerge supports the exclude and generate functionality of srec yet? 

Adding dfu service to mbed classic DID work for repeat uploads

So It would seem DFU is slightly broken atm?

BTW really excited by the new mbed direction, great job everyone.

**Comment by rgrover** [comment]
@jacobrosenthal:
merge_hex.py (above) has very basic functionality. So it is not a general replacement for srec_cat.
if mbed-classic applications are able to drive DFU with the same bootloader, then it would mean something's not working when mbedOS applications try to trigger the bootloader. THis should be easier to investigate. Thanks for this testing!

**Comment by andresag01** [comment]
@jacobrosenthal: Thank you for trying DFU and reporting this issue. We were able to reproduce the problem using the GCC compiler and have been able to identify the source of the problem. We will shortly be pushing a patch to fix this. In the mean time, we have also done the same exercise using ARMCC and DFU seems to work with that setting.

**Comment by rgrover** [comment]
@jacobrosenthal Please retry with the latest of ble-nrf51822. (v2.0.4)

**Comment by jacobrosenthal** [comment]
I can confirm repeatable dfu now :)

Thanks all.
