### ISSUE TITLE
error: minar-platform-posix not available

### ISSUE THREAD

**Issue by jacobrosenthal** [ARMmbed/ble-examples#53]
Looks like (all?) examples are currently broken
Filed upstream here: https://github.com/ARMmbed/minar-platform/issues/4

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-1769

**Comment by janjongboom** [comment]
@jacobrosenthal You'll need to run a `yt target XYZ` first. There's a tracking bug for yotta that should give a better error message: ARMmbed/yotta#645
