### ISSUE TITLE
can't install nrf51dk-gcc target as mentioned in the README

### ISSUE THREAD

**Issue by jrobeson** [ARMmbed/ble-examples#6]
```bash
~/w/l/s/h/ytest on master ⨯ yotta target nrf51dk-gcc                                                                        
~/w/l/s/h/ytest on master ⨯ yotta install                                              
info: get versions for nrf51dk-gcc
error: could not install target nrf51dk-gcc at * for nrf51dk-gcc
error: nrf51dk-gcc does not exist in the targets registry. Check that the name is correct, and that it has been published.
```

**Comment by simonqhughes** [comment]
ARM Internal Ref: IOTSFW-1076

**Comment by andresag01** [comment]
We are aware of this issue. Currently there is no publicly available nrf51dk-gcc target due to some issues with SoftDevice. However, all the examples should build for other targets that are public.

**Comment by jrobeson** [comment]
some issues? if they aren't going to be fixed soon, then the README file should be adjusted

**Comment by andresag01** [comment]
Apologies for any inconvenience, but the issues are to do with licensing rather than technical ones. However, we do expect these to be resolved very soon.

**Comment by rgrover** [comment]
yotta targets related to the nRF51822 family have been published and made public
