### ISSUE TITLE
Connect to BLE_LED using name of device

### ISSUE THREAD

**Issue by LiyouZhou** [ARMmbed/ble-examples#60]
For the BLE_LEDBlinker example
Currently we require the user to find out the mac address of the BLE_LED device and modify main.cpp
 https://github.com/ARMmbed/ble-examples/blob/master/BLE_LEDBlinker/source/main.cpp#L31

It is not always obvious how you can obtain the mac address of a device.
Also as the code is currently written, it is not obvious which bit of the mac address you need to enter.

We can eliminate the complication for the user by just using DEVICE_NAME="LED" to identify the led device. The user can still change it if he wants to uniquely identify his own address, but it saves a lot of trouble for most beginners.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2287

**Comment by pan-** [comment]
Done (https://github.com/ARMmbed/ble-examples/pull/65)
