### ISSUE TITLE
Serial seems to crash app

### ISSUE THREAD

**Issue by PeterKenyon** [ARMmbed/ble-examples#76]
I tried the ble_heartrate and it works really well - great BUT
I added one line and it crashes on a connection
Serial dbg(p9, p11)
This is on the mkit device

**Comment by PeterKenyon** [comment]
Interestingly RawSerial dbg(pc, NC) doesn't cause the same problem

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2576

**Comment by PeterKenyon** [comment]
I'm wondering if this is the S110 issue - I will check again?

**Comment by PeterKenyon** [comment]
Yep using the S110 means that printf works as expected - possibly not recommended tho
