### ISSUE TITLE
Cannot get DeviceInformationService to work

### ISSUE THREAD

**Issue by PeterKenyon** [ARMmbed/ble-examples#78]
Just adding the DeviceInformationService seems to crash the examples, and I cant find an example of it being used anywhere.
The crash occurs when a device connects but before device discovery

**Comment by PeterKenyon** [comment]
I have pruned the DeviceInformationService class and removed hardwareRevision firmwareRevision and softwareRevision Characteristics and now I can connect and discover and read just fine. Is there some limit somewhere, this is very odd behaviour

[DeviceInformationService.h.txt](https://github.com/ARMmbed/ble-examples/files/304924/DeviceInformationService.h.txt)

**Comment by PeterKenyon** [comment]
running using yt debug on connect I hit a __BKPT(0) in
/yotta_modules/mbed-drivers/source/retarget.cpp:568
investigating further...

**Comment by pan-** [comment]
@PeterKenyon It looks like you have memory issues, the memory available on mkit is very small.

Basically with the default configuration, there is just 4k of RAM available for the application (2k are used by the stack and 10k are used by the soft device). If you use printf, it will use 1k of RAM and other parts of mbed OS also use RAM.

The first things you can do are:
* switch to softdevice s110 (explanations here: https://github.com/ARMmbed/target-nrf51822/blob/master/nordic-nrf51822-32k-gcc/switch-softdevice.md). This will save you 2k of RAM.
* Call `setbuf(stdout, NULL)` before any stdio call. It will save you 1k of RAM.

**Comment by PeterKenyon** [comment]
Solved, It was indeed a memory issue as pan described. you need to add a config.json file with the S110 device and life is good again Wow! see #issue80
