### ISSUE TITLE
The mbedtls/* definition in file .mbedignore causes a compile error

### ISSUE THREAD

**Issue by ccchang12** [ARMmbed/ble-examples#83]
I compile BLE_BatteryLevel example for target NUMAKER_PFM_NUC472 but get a error.

The root cause is the NUC472 supports H/W SHA and need to include mbedtls header. Due to the mbedtls/* definition in file .mbedignore, the H/W SHA code cannot find the header and encounters an error. Please remove the mbedtls/* definition to fix this issue.

Below is the compile error message.

......
Scan: mbed
Scan: env
Compile [ 73.6%]: sha1_alt.c
[ERROR] .\mbed-os\targets\TARGET_NUVOTON\TARGET_NUC472\crypto\sha\sha1_alt.c:21:28: fatal error: mbedtls/config.h: No such file or directory
compilation terminated.
[mbed] ERROR: "python" returned error code 1.
[mbed] ERROR: Command "python -u C:\Users\cczhang\mbed\mbed-os-example-ble\BLE_BatteryLevel\mbed-os\tools\make.py -t GCC_ARM -m NUMAKER_PFM_NUC472 --source . --build .\BUILD\NUMAKER_PFM_NUC472\GCC_ARM" in "C:\Users\cczhang\mbed\mbed-os-example-ble\BLE_BatteryLevel"

**Comment by pan-** [comment]
@ccchang12 I think it is the wrong repository, you can open a new ticket in this one  https://github.com/ARMmbed/mbed-os-example-ble and close this issue.

**Comment by ccchang12** [comment]
@pan- I just clone a new repository from your provided link again, the mbedtls/* definition is still exist in file .mbedignore.

cczhang@cczhang-VAIO MINGW64 ~/mbed/test/mbed-os-example-ble/BLE_BatteryLevel (master)
$ cat .mbedignore
mbed-os/features/net/*
mbed-os/uvisor-mbed-lib/*
mbed-os/frameworks/*
mbed-os/features/mbedtls/*

**Comment by pan-** [comment]
@ccchang12 Apologies for my poor previous comment. 
This repository contains the BLE examples for mbed-os 3. 
You are facing an issue compiling the BLE_BatteryLevel example with mbed OS 5. 

The repository containing BLE examples for mbed-os 5 is [here](https://github.com/ARMmbed/ble-examples). I was suggesting you to report your issue in this repository so once a fix will be available you will be able to verify it and I can keep track of the work being done in the right place.

**Comment by ccchang12** [comment]
@pan- Thanks for your comments. I will close this issue and open a new issue in the right mbed-os 5 repository .
