### ISSUE TITLE
Syntax to manually write to a Characteristic

### ISSUE THREAD

**Issue by georgeedwards** [ARMmbed/ble-examples#9]
What is the Syntax to manually update the characteristics from the main program loop? I have the following :

    ble.updateCharacteristicValue(myChar.getValueHandle(), &hrmCounter, sizeof(hrmCounter));

Which isn't working, what should this be?

**Comment by rgrover** [comment]
`ble.gattServer().write()`
https://github.com/ARMmbed/ble/blob/master/ble/GattServer.h#L135

**Comment by georgeedwards** [comment]
How do you specify the Characteristic to write too?

**Comment by rgrover** [comment]
use the getValueHandle() method of GattCharacteristic. You'll find several examples of this if you search.
